# os/.cargo/config
[build]
target = "riscv64gc-unknown-none-elf"
# target = "x86_64-unknown-linux-gnu"
[target.riscv64gc-unknown-none-elf]
 rustflags = [
     "-Clink-arg=-Tsrc/linker.ld", "-Cforce-frame-pointers=yes"
 ]
